#pragma once

#include <algorithm>
#include <array>
#include <cfloat>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <functional>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

#include <fmt/core.h>

#include "../src/aabb.h"
#include "../src/color.h"
#include "../src/element.h"
#include "../src/file_obj.h"
#include "../src/intersection.h"
#include "../src/line.h"
#include "../src/mesh.h"
#include "../src/obb.h"
#include "../src/plane.h"
#include "../src/point.h"
#include "../src/polyline.h"
#include "../src/session.h"
#include "../src/spatial_bvh.h"
#include "../src/spatial_rtree.h"
#include "../src/tolerance.h"
#include "../src/tree.h"
#include "../src/vector.h"
#include "../src/xform.h"
