// This file is @generated by prost-build.
/// One solid feature of an element, added or taken away, in the element's frame.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionFeatureSolid {
    /// The element that put it there, so its next feature replaces it; empty for the element's own
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// The closed solid; empty for a feature of drills alone
    #[prost(message, optional, tag = "2")]
    pub mesh: ::core::option::Option<::session_rust::proto::Mesh>,
    /// A profile feature's closed loops, extruded along extrusion
    #[prost(message, repeated, tag = "3")]
    pub profile: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// The profile's extrusion
    #[prost(message, optional, tag = "4")]
    pub extrusion: ::core::option::Option<::session_rust::proto::Vector>,
    /// SolidOperation: 0 intersect, 1 add, 2 subtract
    #[prost(int32, tag = "5")]
    pub operation: i32,
    /// Boolean tolerance
    #[prost(double, tag = "6")]
    pub tolerance: f64,
    /// Round holes kept as axes, exact in the BRep
    #[prost(message, repeated, tag = "7")]
    pub drills: ::prost::alloc::vec::Vec<::session_rust::proto::Line>,
    /// Radius of the drills
    #[prost(double, tag = "8")]
    pub drill_radius: f64,
    /// Chord tolerance the drills are meshed at
    #[prost(double, tag = "9")]
    pub drill_tolerance: f64,
}
/// A plane an element is cut by, keeping the side its normal points to, in the element's frame.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionFeaturePlane {
    /// The element that put it there, so its next feature replaces it
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// The cutting plane; the element keeps the side its normal points to
    #[prost(message, optional, tag = "2")]
    pub plane: ::core::option::Option<::session_rust::proto::Plane>,
}
/// The state of a Beam beyond the kernel Element: its axis, section and cuts.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Beam {
    #[prost(message, repeated, tag = "7")]
    pub solid_features: ::prost::alloc::vec::Vec<InteractionFeatureSolid>,
    /// The planes other elements cut it by
    #[prost(message, repeated, tag = "8")]
    pub plane_features: ::prost::alloc::vec::Vec<InteractionFeaturePlane>,
    /// Centreline, one segment per span
    #[prost(message, optional, tag = "1")]
    pub axis: ::core::option::Option<::session_rust::proto::Polyline>,
    /// Section half-width per segment
    #[prost(double, repeated, tag = "2")]
    pub radii: ::prost::alloc::vec::Vec<f64>,
    /// Section up direction per segment
    #[prost(message, repeated, tag = "3")]
    pub directions: ::prost::alloc::vec::Vec<::session_rust::proto::Vector>,
    /// 0 crossing only, 1 side-to-end and end-to-end, -1 any
    #[prost(int32, tag = "4")]
    pub allowed_type: i32,
    /// Planes the solid is cut by, each keeping the side its normal points to
    #[prost(message, repeated, tag = "5")]
    pub cuts: ::prost::alloc::vec::Vec<::session_rust::proto::Plane>,
    /// Section loops in the profile frame, loop 0 the outline, then holes; empty takes the square of the radius
    #[prost(message, repeated, tag = "6")]
    pub profile: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
/// The state of a BeamVariable beyond the kernel Element: its straight axis, the sections lofted along it and its cuts.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BeamVariable {
    /// Straight reference line from the first section to the last
    #[prost(message, optional, tag = "1")]
    pub axis: ::core::option::Option<::session_rust::proto::Line>,
    /// Closed rings with one point count, one per station in axis order
    #[prost(message, repeated, tag = "2")]
    pub sections: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// Planes the solid is cut by, each keeping the side its normal points to
    #[prost(message, repeated, tag = "3")]
    pub cuts: ::prost::alloc::vec::Vec<::session_rust::proto::Plane>,
    /// Solids and drills the joints cut out of it, in the beam's frame
    #[prost(message, repeated, tag = "4")]
    pub solid_features: ::prost::alloc::vec::Vec<InteractionFeatureSolid>,
    /// The planes other elements cut it by
    #[prost(message, repeated, tag = "5")]
    pub plane_features: ::prost::alloc::vec::Vec<InteractionFeaturePlane>,
}
/// The state of a Block beyond the kernel Element: the closed loops its solid is lofted between and its cuts.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(message, optional, tag = "4")]
    pub source_mesh: ::core::option::Option<::session_rust::proto::Mesh>,
    #[prost(message, repeated, tag = "3")]
    pub solid_features: ::prost::alloc::vec::Vec<InteractionFeatureSolid>,
    /// The planes other elements cut it by
    #[prost(message, repeated, tag = "5")]
    pub plane_features: ::prost::alloc::vec::Vec<InteractionFeaturePlane>,
    /// Bottom loop, top loop, then their holes paired in order
    #[prost(message, repeated, tag = "1")]
    pub loops: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// Planes the solid is cut by, each keeping the side its normal points to
    #[prost(message, repeated, tag = "2")]
    pub cuts: ::prost::alloc::vec::Vec<::session_rust::proto::Plane>,
}
/// The state of a Column beyond the kernel Element: its axis, section, cuts and solid features.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Column {
    #[prost(message, repeated, tag = "6")]
    pub solid_features: ::prost::alloc::vec::Vec<InteractionFeatureSolid>,
    /// The planes other elements cut it by
    #[prost(message, repeated, tag = "10")]
    pub plane_features: ::prost::alloc::vec::Vec<InteractionFeaturePlane>,
    /// Centreline, base to head
    #[prost(message, optional, tag = "1")]
    pub axis: ::core::option::Option<::session_rust::proto::Line>,
    /// Closed cross-section about the axis base
    #[prost(message, optional, tag = "2")]
    pub section: ::core::option::Option<::session_rust::proto::Polyline>,
    /// Planes the solid is cut by, each keeping the side its normal points to
    #[prost(message, repeated, tag = "3")]
    pub cuts: ::prost::alloc::vec::Vec<::session_rust::proto::Plane>,
    /// Section loops in the profile frame the section was placed from; empty when the section was given
    #[prost(message, repeated, tag = "4")]
    pub profile: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// Degrees the profile x axis turns from world x about the axis
    #[prost(double, tag = "5")]
    pub rotation: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Joint {
    #[prost(message, repeated, tag = "1")]
    pub loops: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    #[prost(message, repeated, tag = "2")]
    pub cuts: ::prost::alloc::vec::Vec<::session_rust::proto::Plane>,
    #[prost(string, repeated, tag = "3")]
    pub targets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub connections: ::prost::alloc::vec::Vec<::session_rust::proto::Interaction>,
    #[prost(message, optional, tag = "5")]
    pub beam_feature: ::core::option::Option<::session_rust::proto::Interaction>,
    #[prost(int32, tag = "6")]
    pub variant: i32,
    #[prost(double, tag = "7")]
    pub division_distance: f64,
    #[prost(double, tag = "8")]
    pub shift: f64,
    #[prost(double, tag = "9")]
    pub line_radius: f64,
    #[prost(bool, tag = "10")]
    pub generated: bool,
    #[prost(string, tag = "11")]
    pub kind: ::prost::alloc::string::String,
    #[prost(double, tag = "12")]
    pub chord_tolerance: f64,
    #[prost(message, repeated, tag = "13")]
    pub cutter_profile: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    #[prost(message, optional, tag = "14")]
    pub cutter_extrusion: ::core::option::Option<::session_rust::proto::Vector>,
    #[prost(message, repeated, tag = "15")]
    pub drill_lines: ::prost::alloc::vec::Vec<::session_rust::proto::Line>,
    #[prost(int32, optional, tag = "16")]
    pub operation: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "17")]
    pub plate_parameters: ::core::option::Option<JointPlateParameters>,
    /// A connector's own solids as bottom, top loop pairs
    #[prost(message, repeated, tag = "18")]
    pub parts: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// A connector's cutters, one entry per target in targets order
    #[prost(message, repeated, tag = "19")]
    pub cutters: ::prost::alloc::vec::Vec<JointCutter>,
    /// How far a connector's holes run past its pins where they leave a target
    #[prost(double, tag = "20")]
    pub drill_overshoot: f64,
    /// Cuts into a connector's own parts, a cross lap's slots say, in the connector's frame
    #[prost(message, repeated, tag = "21")]
    pub solid_features: ::prost::alloc::vec::Vec<InteractionFeatureSolid>,
    /// A connector of pins: its drill lines are pre-drilled holes in its targets, never cut
    #[prost(bool, tag = "23")]
    pub pre_drill: bool,
}
/// The solids a connector cuts out of one target, as bottom, top loop pairs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JointCutter {
    #[prost(message, repeated, tag = "1")]
    pub loops: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JointPlateParameters {
    #[prost(string, tag = "1")]
    pub library: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub contact_type: i32,
    #[prost(int32, tag = "3")]
    pub divisions: i32,
    #[prost(double, tag = "4")]
    pub taper: f64,
    #[prost(bool, tag = "5")]
    pub chamfer: bool,
    #[prost(bool, optional, tag = "6")]
    pub modify_outline: ::core::option::Option<bool>,
    #[prost(double, repeated, tag = "7")]
    pub x: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, repeated, tag = "8")]
    pub y: ::prost::alloc::vec::Vec<f64>,
    #[prost(double, repeated, tag = "9")]
    pub z: ::prost::alloc::vec::Vec<f64>,
    #[prost(bool, tag = "10")]
    pub disable_divisions: bool,
    #[prost(double, tag = "11")]
    pub distance_squared: f64,
    #[prost(bool, tag = "12")]
    pub merge_with_joint: bool,
    #[prost(message, repeated, tag = "13")]
    pub male: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    #[prost(message, repeated, tag = "14")]
    pub female: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
/// The state of a Plate beyond the kernel Element: its two outlines.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Plate {
    #[prost(message, repeated, tag = "4")]
    pub solid_features: ::prost::alloc::vec::Vec<InteractionFeatureSolid>,
    /// Bottom outline
    #[prost(message, optional, tag = "1")]
    pub bottom: ::core::option::Option<::session_rust::proto::Polyline>,
    /// Top outline
    #[prost(message, optional, tag = "2")]
    pub top: ::core::option::Option<::session_rust::proto::Polyline>,
    /// True when the constructor reversed both outlines
    #[prost(bool, tag = "3")]
    pub reversed: bool,
}
/// The state of a Support beyond the kernel Element: its placement and every dimension of the column base.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Support {
    /// Base plate underside centre, z up the column, x along a base plate side
    #[prost(message, optional, tag = "1")]
    pub plane: ::core::option::Option<::session_rust::proto::Plane>,
    /// Base plate underside to head plate top
    #[prost(double, tag = "2")]
    pub height: f64,
    #[prost(double, tag = "3")]
    pub head_plate_diameter: f64,
    #[prost(double, tag = "4")]
    pub head_plate_thickness: f64,
    /// Depth the head plate is let into the column end
    #[prost(double, tag = "5")]
    pub head_plate_recess: f64,
    #[prost(double, tag = "6")]
    pub base_plate_size: f64,
    #[prost(double, tag = "7")]
    pub base_plate_thickness: f64,
    #[prost(double, tag = "8")]
    pub base_plate_hole_diameter: f64,
    /// Centre distance of the anchor drillings along each side
    #[prost(double, tag = "9")]
    pub base_plate_hole_spacing: f64,
    #[prost(double, tag = "10")]
    pub adjustment_nut_across_flats: f64,
    #[prost(double, tag = "11")]
    pub adjustment_nut_top: f64,
    #[prost(double, tag = "12")]
    pub rod_diameter: f64,
    #[prost(double, tag = "13")]
    pub coupling_nut_across_flats: f64,
    #[prost(double, tag = "14")]
    pub coupling_nut_height: f64,
    #[prost(int32, tag = "15")]
    pub pin_count: i32,
    #[prost(double, tag = "16")]
    pub pin_diameter: f64,
    #[prost(double, tag = "17")]
    pub pin_length: f64,
    /// Degrees between a pair of opposed pins
    #[prost(double, tag = "18")]
    pub pin_angle: f64,
    #[prost(double, tag = "19")]
    pub pin_circle_diameter: f64,
    #[prost(double, tag = "20")]
    pub anchor_diameter: f64,
    #[prost(double, tag = "21")]
    pub anchor_embedment: f64,
    #[prost(double, tag = "22")]
    pub chord_tolerance: f64,
}
/// The state of an InteractionContactAxis beyond the kernel Interaction: where two polylines come closest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionContactAxis {
    /// From the closest point on the first element to the closest point on the second
    #[prost(message, optional, tag = "1")]
    pub segment: ::core::option::Option<::session_rust::proto::Line>,
    /// Parameter of the closest point along segment_a, 0..1
    #[prost(double, tag = "2")]
    pub t_a: f64,
    /// Parameter of the closest point along segment_b, 0..1
    #[prost(double, tag = "3")]
    pub t_b: f64,
    /// Which polyline of the first element: a beam has one axis, a plate one outline per face
    #[prost(int32, tag = "4")]
    pub polyline_a: i32,
    /// Segment of that polyline
    #[prost(int32, tag = "5")]
    pub segment_a: i32,
    /// Which polyline of the second element
    #[prost(int32, tag = "6")]
    pub polyline_b: i32,
    /// Segment of that polyline
    #[prost(int32, tag = "7")]
    pub segment_b: i32,
}
/// The state of an InteractionContactCross beyond the kernel Interaction: where two plates' side faces pass through each other.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionContactCross {
    /// The two side faces of the first element, 2 entries
    #[prost(int32, repeated, tag = "1")]
    pub faces_a: ::prost::alloc::vec::Vec<i32>,
    /// The two side faces of the second element, 2 entries
    #[prost(int32, repeated, tag = "2")]
    pub faces_b: ::prost::alloc::vec::Vec<i32>,
    /// Closed quad on the mid-plane
    #[prost(message, optional, tag = "3")]
    pub polygon: ::core::option::Option<::session_rust::proto::Polyline>,
    /// The two perpendicular centrelines of polygon, 2 entries
    #[prost(message, repeated, tag = "4")]
    pub lines: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// The two parallel quads bounding the joint volume, 2 entries
    #[prost(message, repeated, tag = "5")]
    pub volumes: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
/// The state of an InteractionContactFace beyond the kernel Interaction: two coplanar faces in contact and the region they share.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionContactFace {
    #[prost(message, repeated, tag = "5")]
    pub lines: ::prost::alloc::vec::Vec<::session_rust::proto::Line>,
    #[prost(message, repeated, tag = "6")]
    pub volumes: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// Face index on the edge's first element
    #[prost(int32, tag = "1")]
    pub face_a: i32,
    /// Face index on the edge's second element
    #[prost(int32, tag = "2")]
    pub face_b: i32,
    /// ContactType: -1 unknown, 0 side_side, 1 side_top, 2 top_top
    #[prost(int32, tag = "3")]
    pub r#type: i32,
    /// Boolean intersection of the two face outlines, closed, in face_a's plane
    #[prost(message, optional, tag = "4")]
    pub polygon: ::core::option::Option<::session_rust::proto::Polyline>,
}
/// The state of an InteractionFeatureBeam beyond the kernel Interaction: the four volume rectangles cut where two axes meet.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionFeatureBeam {
    /// 0 crossing, 1 side to end, 2 end to end
    #[prost(int32, tag = "1")]
    pub end_type: i32,
    /// 4 rectangles: 2 on the first beam, 2 on the second
    #[prost(message, repeated, tag = "2")]
    pub volumes: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
/// One face's outlines, so a per-face list can repeat.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PolylineList {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
/// One list of ints, so a per-face list can repeat.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntList {
    #[prost(int32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i32>,
}
/// The state of an InteractionFeaturePlate beyond the kernel Interaction, whose name is the joint library variant: the pair, the face contact it was solved from, its parameters, the cut outlines per element per face and the two element features the hosts carry.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InteractionFeaturePlate {
    #[prost(int32, tag = "28")]
    pub target_side: i32,
    /// The male element, by guid
    #[prost(string, tag = "21")]
    pub element_a: ::prost::alloc::string::String,
    /// The female element, by guid
    #[prost(string, tag = "22")]
    pub element_b: ::prost::alloc::string::String,
    /// The face contact the joint was solved from, a solver field
    #[prost(message, optional, tag = "23")]
    pub contact: ::core::option::Option<InteractionContactFace>,
    /// 2 entries: what the male host and the female host carry
    #[prost(message, repeated, tag = "24")]
    pub element_features: ::prost::alloc::vec::Vec<
        ::session_rust::proto::ElementFeature,
    >,
    /// Refined solver code: 11/12/13 side-side, 20 top-side, 30 cross, 40 top-top
    #[prost(int32, tag = "1")]
    pub joint_type: i32,
    /// Cross joints: the second side face of each element, 2 entries
    #[prost(int32, repeated, tag = "3")]
    pub cross_faces: ::prost::alloc::vec::Vec<i32>,
    /// The two alignment lines, one per element
    #[prost(message, repeated, tag = "4")]
    pub joint_lines: ::prost::alloc::vec::Vec<::session_rust::proto::Line>,
    /// 4 volume rectangles, an empty polyline where the solver set none
    #[prost(message, repeated, tag = "5")]
    pub joint_volumes: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// Male cut outlines: \[0\] bottom face, \[1\] top face
    #[prost(message, repeated, tag = "6")]
    pub male_outlines: ::prost::alloc::vec::Vec<PolylineList>,
    /// Female cut outlines, laid out the same
    #[prost(message, repeated, tag = "7")]
    pub female_outlines: ::prost::alloc::vec::Vec<PolylineList>,
    /// One FabricationType per male outline, per face
    #[prost(message, repeated, tag = "8")]
    pub male_fabrication_types: ::prost::alloc::vec::Vec<IntList>,
    /// One FabricationType per female outline, per face
    #[prost(message, repeated, tag = "9")]
    pub female_fabrication_types: ::prost::alloc::vec::Vec<IntList>,
    /// Teeth or notches along the joint line
    #[prost(int32, tag = "10")]
    pub divisions: i32,
    /// Lateral offset of the pattern, 0..1
    #[prost(double, tag = "11")]
    pub shift: f64,
    /// Length of the joint line
    #[prost(double, tag = "12")]
    pub length: f64,
    /// Spacing between divisions
    #[prost(double, tag = "13")]
    pub division_length: f64,
    /// Scale of the unit-box geometry, 3 entries
    #[prost(double, repeated, tag = "14")]
    pub scale: ::prost::alloc::vec::Vec<f64>,
    /// True when the axial size is pinned to unit_scale_distance
    #[prost(bool, tag = "15")]
    pub unit_scale: bool,
    /// The axial size a unit-scale variant is pinned to
    #[prost(double, tag = "16")]
    pub unit_scale_distance: f64,
    /// Guids of the joints this one is linked with (three-valence shadows)
    #[prost(string, repeated, tag = "26")]
    pub linked_joints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Per linked joint, the vertex ranges as flat quads
    #[prost(message, repeated, tag = "18")]
    pub linked_joints_seq: ::prost::alloc::vec::Vec<IntList>,
    /// True when this joint is the link of a three-valence group
    #[prost(bool, tag = "19")]
    pub link: bool,
    /// True when the outlines are already in world space
    #[prost(bool, tag = "20")]
    pub no_orient: bool,
}
/// The state of an InteractionFeaturePlateBeam beyond the kernel Interaction; nothing computed yet.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InteractionFeaturePlateBeam {}
/// User joint outlines for one family: male and female (face0, face1) pairs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CustomJoint {
    /// "ss_e_ip", "ss_e_op", "ts_e_p", "cr_c_ip", "tt_e_p", "ss_e_r" or "b"
    #[prost(string, tag = "1")]
    pub family: ::prost::alloc::string::String,
    /// Male outline pairs
    #[prost(message, repeated, tag = "2")]
    pub male: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
    /// Female outline pairs
    #[prost(message, repeated, tag = "3")]
    pub female: ::prost::alloc::vec::Vec<::session_rust::proto::Polyline>,
}
/// Every tunable of the solver, as the dataset yml sets it; written with the scene so a file records what produced it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settings {
    /// 0 face_to_face, 1 cross_joint, 2 face_to_face_then_cross
    #[prost(int32, tag = "1")]
    pub search_type: i32,
    /// Joint-family triples \[division_length, shift, joint id\], 7 families
    #[prost(double, repeated, tag = "2")]
    pub joint_parameters: ::prost::alloc::vec::Vec<f64>,
    /// \[width, height, length\] per joint type, or one triple for all
    #[prost(double, repeated, tag = "3")]
    pub joint_volume_extension: ::prost::alloc::vec::Vec<f64>,
    /// \[sx, sy, sz\], 3 entries
    #[prost(double, repeated, tag = "4")]
    pub joint_scale: ::prost::alloc::vec::Vec<f64>,
    /// Degrees, rotated-joint threshold
    #[prost(double, tag = "5")]
    pub dihedral_angle: f64,
    /// Force the rotated geometry path
    #[prost(bool, tag = "6")]
    pub all_treated_as_rotated: bool,
    /// Averaged plane for rotated joints
    #[prost(bool, tag = "7")]
    pub rotated_joint_as_average: bool,
    /// AABB inflation and point-merge tolerance, mm
    #[prost(double, tag = "8")]
    pub distance: f64,
    /// Squared coplanarity tolerance, mm²
    #[prost(double, tag = "9")]
    pub distance_squared: f64,
    /// Angular tolerance, radians
    #[prost(double, tag = "10")]
    pub angle: f64,
    /// Consecutive duplicate removal when reading an obj
    #[prost(double, tag = "11")]
    pub duplicate_points_tolerance: f64,
    /// Joints with a shorter centreline are dropped
    #[prost(double, tag = "12")]
    pub limit_min_joint_length: f64,
    /// mm to int64 for the 2D boolean
    #[prost(int64, tag = "13")]
    pub clipper_scale: i64,
    /// Overlaps at or below this area are not a contact
    #[prost(double, tag = "14")]
    pub clipper_area: f64,
    /// \[radius, allowed type, min_distance, volume_length, cross_or_side_to_end, flip_male\]
    #[prost(double, repeated, tag = "15")]
    pub beams: ::prost::alloc::vec::Vec<f64>,
    /// User joint outlines, in family order
    #[prost(message, repeated, tag = "16")]
    pub custom_joints: ::prost::alloc::vec::Vec<CustomJoint>,
}
/// A wood scene on the wire: fields 1..9 are session_proto.Session field for field, so any
/// Session reader opens the file, the interactions included, and drops the settings as an unknown field.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WoodSession {
    /// Session name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Unique identifier
    #[prost(string, tag = "2")]
    pub guid: ::prost::alloc::string::String,
    /// Collection of all geometry objects
    #[prost(message, optional, tag = "3")]
    pub objects: ::core::option::Option<::session_rust::proto::Objects>,
    /// Tree hierarchy structure
    #[prost(message, optional, tag = "4")]
    pub tree: ::core::option::Option<::session_rust::proto::Tree>,
    /// Graph relationships
    #[prost(message, optional, tag = "5")]
    pub graph: ::core::option::Option<::session_rust::proto::Graph>,
    /// Simplified BVH representation
    #[prost(message, repeated, tag = "6")]
    pub bvh_boxes: ::prost::alloc::vec::Vec<::session_rust::proto::BoundingBox>,
    /// Local transforms in Session::order() sequence
    #[prost(message, repeated, tag = "7")]
    pub xforms: ::prost::alloc::vec::Vec<::session_rust::proto::XformEntry>,
    /// Shared element definitions the instances place, each in its own frame
    #[prost(message, optional, tag = "8")]
    pub definitions: ::core::option::Option<::session_rust::proto::Objects>,
    /// Interactions per graph edge, in edge-guid order; wood types in interaction_data
    #[prost(message, repeated, tag = "9")]
    pub interactions: ::prost::alloc::vec::Vec<::session_rust::proto::InteractionEntry>,
    /// The solver settings the scene was solved with
    #[prost(message, optional, tag = "101")]
    pub settings: ::core::option::Option<Settings>,
    /// Plate pairs by position the solver classifies; empty lets it search
    #[prost(message, repeated, tag = "102")]
    pub adjacency: ::prost::alloc::vec::Vec<PlatePair>,
    /// The three-valence instruction row, then one row of plate positions per group
    #[prost(message, repeated, tag = "103")]
    pub three_valence: ::prost::alloc::vec::Vec<PlateGroup>,
}
/// Two plate positions in world_elements<Plate>() order.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlatePair {
    #[prost(int32, tag = "1")]
    pub first: i32,
    #[prost(int32, tag = "2")]
    pub second: i32,
}
/// A row of plate positions, or the three-valence instruction row.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlateGroup {
    #[prost(int32, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<i32>,
}
